In [40]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time
import os

# Current dir
current_dir = os.getcwd()

options = webdriver.ChromeOptions()
options.add_argument("--headless")
driver = webdriver.Chrome(
    service = Service(ChromeDriverManager().install()),
    options = options
)
options.add_argument("--headless")
url ='https://apps.bea.gov/iTable/?reqid=70&step=1&isuri=1&acrdn=6#eyJhcHBpZCI6NzAsInN0ZXBzIjpbMSwyOSwyNSwzMSwyNiwyNywzMF0sImRhdGEiOltbIlRhYmxlSWQiLCIzNiJdLFsiTWFqb3JfQXJlYSIsIjAiXSxbIlN0YXRlIixbIjAiXV0sWyJBcmVhIixbIlhYIl1dLFsiU3RhdGlzdGljIixbIjMiXV0sWyJVbml0X29mX21lYXN1cmUiLCJMZXZlbHMiXSxbIlllYXIiLFsiMjAxOCJdXSxbIlllYXJCZWdpbiIsIi0xIl0sWyJZZWFyX0VuZCIsIi0xIl1dfQ=='
driver.get(url)

In [41]:
# Esperar a que la tabla cargue
time.sleep(10)

# Extraer filas
rows = driver.find_elements(By.CSS_SELECTOR, 'table#DataTbl tbody tr')

datos = []
for row in rows:
    cols = row.find_elements(By.TAG_NAME, 'td')
    if len(cols) >= 4:
        cp = cols[0].text.strip()  
        estado = cols[1].text.strip().replace(' *', '').replace(' ', '')
        q1 = cols[2].text.strip().replace('.', '') 
        q1 = int(float(q1.replace(',', '.')) * 1_000_000_000)
        q2 = cols[3].text.strip().replace('.', '') 
        q2 = int(float(q2.replace(',', '.')) * 1_000_000_000) 
        datos.append([cp, estado, q1, q2])

# Crear DataFrame
capital_personal_income = pd.DataFrame(datos, columns=["cp", "estado", "Q1", "Q2"])
print(capital_personal_income)

# Cerrar navegador
driver.quit()

       cp              estado           Q1           Q2
0   00000        UnitedStates  52443000000  52986000000
1   01000             Alabama  40825000000  41094000000
2   02000              Alaska  58076000000  58490000000
3   04000             Arizona  44628000000  44961000000
4   05000            Arkansas  42434000000  42762000000
5   06000          California  59735000000  60612000000
6   08000            Colorado  56452000000  57262000000
7   09000         Connecticut  71081000000  71679000000
8   10000            Delaware  51725000000  52313000000
9   11000  DistrictofColumbia  80946000000  81715000000
10  12000             Florida  50086000000  50560000000
11  13000             Georgia  45853000000  46325000000
12  15000              Hawaii  51061000000  51439000000
13  16000               Idaho  42652000000  43005000000
14  17000            Illinois  55132000000  55880000000
15  18000             Indiana  46049000000  46288000000
16  19000                Iowa  47973000000  48452000000
17  20000              Kansas  49399000000  50005000000
18  21000            Kentucky  41189000000  41590000000
19  22000           Louisiana  44716000000  45343000000
20  23000               Maine  47115000000  47551000000
21  24000            Maryland  59189000000  59690000000
22  25000       Massachusetts  68245000000  68799000000
23  26000            Michigan  46671000000  46917000000
24  27000           Minnesota  55151000000  55881000000
25  28000         Mississippi  37071000000  37479000000
26  29000            Missouri  45796000000  46639000000
27  30000             Montana  46504000000  46993000000
28  31000            Nebraska  50476000000  50864000000
29  32000              Nevada  48716000000  48879000000
30  33000        NewHampshire  59798000000  60014000000
31  34000           NewJersey  63255000000  63788000000
32  35000           NewMexico  40314000000  40730000000
33  36000             NewYork  63330000000  63986000000
34  37000       NorthCarolina  45226000000  45771000000
35  38000         NorthDakota  53653000000  54635000000
36  39000                Ohio  47112000000  47529000000
37  40000            Oklahoma  45333000000  45715000000
38  41000              Oregon  49343000000  49893000000
39  42000        Pennsylvania  53550000000  54083000000
40  44000         RhodeIsland  51741000000  51870000000
41  45000       SouthCarolina  43136000000  43525000000
42  46000         SouthDakota  50773000000  50865000000
43  47000           Tennessee  45732000000  46072000000
44  48000               Texas  50365000000  50969000000
45  49000                Utah  44732000000  45202000000
46  50000             Vermont  50941000000  51479000000
47  51000            Virginia  55380000000  55789000000
48  53000          Washington  58871000000  59261000000
49  54000        WestVirginia  40006000000  40625000000
50  55000           Wisconsin  49984000000  50140000000
51  56000             Wyoming  57821000000  58729000000
52  91000          NewEngland  64331999999  64822000000
53  92000             Mideast  60298000000  60881000000
54  93000          GreatLakes  49411000000  49822000000
55  94000              Plains  49977000000  50639000000
56  95000           Southeast  46464000000  46914000000
57  96000           Southwest  48415000000  48944000000
58  97000       RockyMountain  50628000000  51257000000
59  98000             FarWest  58020000000  58748000000

In [42]:
capital_personal_income['january'] = capital_personal_income['Q1'] / 3

capital_personal_income['february'] = capital_personal_income['Q1'] / 3

capital_personal_income['march'] = capital_personal_income['Q1'] / 3

capital_personal_income['april'] = capital_personal_income['Q2'] / 3

capital_personal_income['may'] = capital_personal_income['Q2'] / 3

capital_personal_income = capital_personal_income.drop(columns = ["Q1", "Q2"])

capital_personal_income

,cp,estado,january,february,march,april,may
0,00000,UnitedStates,1.748100e+10,1.748100e+10,1.748100e+10,1.766200e+10,1.766200e+10
1,01000,Alabama,1.360833e+10,1.360833e+10,1.360833e+10,1.369800e+10,1.369800e+10
2,02000,Alaska,1.935867e+10,1.935867e+10,1.935867e+10,1.949667e+10,1.949667e+10
3,04000,Arizona,1.487600e+10,1.487600e+10,1.487600e+10,1.498700e+10,1.498700e+10
4,05000,Arkansas,1.414467e+10,1.414467e+10,1.414467e+10,1.425400e+10,1.425400e+10
5,06000,California,1.991167e+10,1.991167e+10,1.991167e+10,2.020400e+10,2.020400e+10
6,08000,Colorado,1.881733e+10,1.881733e+10,1.881733e+10,1.908733e+10,1.908733e+10
7,09000,Connecticut,2.369367e+10,2.369367e+10,2.369367e+10,2.389300e+10,2.389300e+10
8,10000,Delaware,1.724167e+10,1.724167e+10,1.724167e+10,1.743767e+10,1.743767e+10
9,11000,DistrictofColumbia,2.698200e+10,2.698200e+10,2.698200e+10,2.723833e+10,2.723833e+10
10,12000,Florida,1.669533e+10,1.669533e+10,1.669533e+10,1.685333e+10,1.685333e+10
11,13000,Georgia,1.528433e+10,1.528433e+10,1.528433e+10,1.544167e+10,1.544167e+10
12,15000,Hawaii,1.702033e+10,1.702033e+10,1.702033e+10,1.714633e+10,1.714633e+10
13,16000,Idaho,1.421733e+10,1.421733e+10,1.421733e+10,1.433500e+10,1.433500e+10
14,17000,Illinois,1.837733e+10,1.837733e+10,1.837733e+10,1.862667e+10,1.862667e+10
15,18000,Indiana,1.534967e+10,1.534967e+10,1.534967e+10,1.542933e+10,1.542933e+10
16,19000,Iowa,1.599100e+10,1.599100e+10,1.599100e+10,1.615067e+10,1.615067e+10
17,20000,Kansas,1.646633e+10,1.646633e+10,1.646633e+10,1.666833e+10,1.666833e+10
18,21000,Kentucky,1.372967e+10,1.372967e+10,1.372967e+10,1.386333e+10,1.386333e+10
19,22000,Louisiana,1.490533e+10,1.490533e+10,1.490533e+10,1.511433e+10,1.511433e+10
20,23000,Maine,1.570500e+10,1.570500e+10,1.570500e+10,1.585033e+10,1.585033e+10
21,24000,Maryland,1.972967e+10,1.972967e+10,1.972967e+10,1.989667e+10,1.989667e+10
22,25000,Massachusetts,2.274833e+10,2.274833e+10,2.274833e+10,2.293300e+10,2.293300e+10
23,26000,Michigan,1.555700e+10,1.555700e+10,1.555700e+10,1.563900e+10,1.563900e+10
24,27000,Minnesota,1.838367e+10,1.838367e+10,1.838367e+10,1.862700e+10,1.862700e+10
25,28000,Mississippi,1.235700e+10,1.235700e+10,1.235700e+10,1.249300e+10,1.249300e+10
26,29000,Missouri,1.526533e+10,1.526533e+10,1.526533e+10,1.554633e+10,1.554633e+10
27,30000,Montana,1.550133e+10,1.550133e+10,1.550133e+10,1.566433e+10,1.566433e+10
28,31000,Nebraska,1.682533e+10,1.682533e+10,1.682533e+10,1.695467e+10,1.695467e+10
29,32000,Nevada,1.623867e+10,1.623867e+10,1.623867e+10,1.629300e+10,1.629300e+10
30,33000,NewHampshire,1.993267e+10,1.993267e+10,1.993267e+10,2.000467e+10,2.000467e+10
31,34000,NewJersey,2.108500e+10,2.108500e+10,2.108500e+10,2.126267e+10,2.126267e+10
32,35000,NewMexico,1.343800e+10,1.343800e+10,1.343800e+10,1.357667e+10,1.357667e+10
33,36000,NewYork,2.111000e+10,2.111000e+10,2.111000e+10,2.132867e+10,2.132867e+10
34,37000,NorthCarolina,1.507533e+10,1.507533e+10,1.507533e+10,1.525700e+10,1.525700e+10
35,38000,NorthDakota,1.788433e+10,1.788433e+10,1.788433e+10,1.821167e+10,1.821167e+10
36,39000,Ohio,1.570400e+10,1.570400e+10,1.570400e+10,1.584300e+10,1.584300e+10
37,40000,Oklahoma,1.511100e+10,1.511100e+10,1.511100e+10,1.523833e+10,1.523833e+10
38,41000,Oregon,1.644767e+10,1.644767e+10,1.644767e+10,1.663100e+10,1.663100e+10
39,42000,Pennsylvania,1.785000e+10,1.785000e+10,1.785000e+10,1.802767e+10,1.802767e+10
40,44000,RhodeIsland,1.724700e+10,1.724700e+10,1.724700e+10,1.729000e+10,1.729000e+10
41,45000,SouthCarolina,1.437867e+10,1.437867e+10,1.437867e+10,1.450833e+10,1.450833e+10
42,46000,SouthDakota,1.692433e+10,1.692433e+10,1.692433e+10,1.695500e+10,1.695500e+10
43,47000,Tennessee,1.524400e+10,1.524400e+10,1.524400e+10,1.535733e+10,1.535733e+10
44,48000,Texas,1.678833e+10,1.678833e+10,1.678833e+10,1.698967e+10,1.698967e+10
45,49000,Utah,1.491067e+10,1.491067e+10,1.491067e+10,1.506733e+10,1.506733e+10
46,50000,Vermont,1.698033e+10,1.698033e+10,1.698033e+10,1.715967e+10,1.715967e+10
47,51000,Virginia,1.846000e+10,1.846000e+10,1.846000e+10,1.859633e+10,1.859633e+10
48,53000,Washington,1.962367e+10,1.962367e+10,1.962367e+10,1.975367e+10,1.975367e+10
49,54000,WestVirginia,1.333533e+10,1.333533e+10,1.333533e+10,1.354167e+10,1.354167e+10
50,55000,Wisconsin,1.666133e+10,1.666133e+10,1.666133e+10,1.671333e+10,1.671333e+10
51,56000,Wyoming,1.927367e+10,1.927367e+10,1.927367e+10,1.957633e+10,1.957633e+10
52,91000,NewEngland,2.144400e+10,2.144400e+10,2.144400e+10,2.160733e+10,2.160733e+10
53,92000,Mideast,2.009933e+10,2.009933e+10,2.009933e+10,2.029367e+10,2.029367e+10
54,93000,GreatLakes,1.647033e+10,1.647033e+10,1.647033e+10,1.660733e+10,1.660733e+10
55,94000,Plains,1.665900e+10,1.665900e+10,1.665900e+10,1.687967e+10,1.687967e+10
56,95000,Southeast,1.548800e+10,1.548800e+10,1.548800e+10,1.563800e+10,1.563800e+10
57,96000,Southwest,1.613833e+10,1.613833e+10,1.613833e+10,1.631467e+10,1.631467e+10
58,97000,RockyMountain,1.687600e+10,1.687600e+10,1.687600e+10,1.708567e+10,1.708567e+10
59,98000,FarWest,1.934000e+10,1.934000e+10,1.934000e+10,1.958267e+10,1.958267e+10

In [43]:
## Guardar en CSV
# Path
capital_personal_income_path = os.path.join(current_dir, '../../data/raw/macrodata')
# Crear un directorio si no existe
os.makedirs(capital_personal_income_path, exist_ok=True)
# Archivo CSV
capital_personal_income_file = os.path.join(capital_personal_income_path, "riqueza_per_capita.csv")
# Guardar dataframe en CSV
capital_personal_income.to_csv(capital_personal_income_file, index=False)